### ISSUE TITLE
Export Pattern and Token?

### ISSUE THREAD

**Issue by sol** [Deewiant/glob#10]
For https://github.com/sol/hpack/issues/101 I need to decide whether a given glob pattern contains wildcards or refers to a literal file.  I assume this will be possible if we expose `Pattern(..)` and `Token(..)`. 

I'm ok if we expose them from an `Internal` module, if that is what you prefer.

I'm also happy with any other solution that allows me to decide whether a given glob pattern contains wildcards.

**Comment by Deewiant** [comment]
`Pattern` and `Token` aren't really meant to be freely played with so it should definitely be from an `Internal` module.

But this seems like a reasonable enough use case to have something more specific for. I'm not sure if something as straightforward as `hasWildcards :: Pattern -> Bool` is the best solution but I can't think of anything significantly better either. Any opinions?

**Comment by hdgarrood** [comment]
This is relevant to the PureScript compiler too - the compiler passes command line arguments to this library, in order to achieve consistent globbing across platforms, so we generally recommend that people quote globs in command line arguments to stop them from being expanded by the shell. However sometimes people forget to do this, so `Glob` gets a large number of literal file paths, which still works, but takes a very long time. If there were a `hasWildcards` function like this we could skip globbing for these literals, which would solve the performance issue.

I would maybe suggest that it it be `isLiteral :: Pattern -> Bool` rather than `hasWildcards :: Pattern -> Bool`, though, as what counts as a "wildcard" might be a little ambiguous; I can imagine people disagreeing about whether `[a-z]` counts. I'm imagining that this `isLiteral` function would return `True` iff the given `Pattern` contains only `Literal`, `ExtSeparator`, `PathSeparator`, and `LongLiteral` constructors.

(Separately, though, we wouldn't need to bother with all this if the `globX` functions could be optimized to avoid making unnecessary calls such as listing directory contents while globbing with `Pattern`s which are just literal file paths. Would you accept a PR which tried to achieve this? Should I open another issue?)

**Comment by Deewiant** [comment]
Feel free to optimize the `globX` functions, that's a sensible thing to do in its own right. I do think you should open another issue for that though since it doesn't seem like that optimization would resolve https://github.com/sol/hpack/issues/101.

The thing about `[a-z]` and the general fact that there are different ways of doing non-literal matching is what gave me pause for `hasWildcards` and also makes me wonder about `isLiteral`. Mostly it's the weirdness of having this rather specific `Bool`-returning function. Is it conceivable for someone to be interested in `hasRecursiveWildcards` or whatever? A possibility that occurred to me was exposing a view similar to `[Token]` without giving away the actual internals, but that comes with design questions of its own.

**Comment by hdgarrood** [comment]
> Is it conceivable for someone to be interested in hasRecursiveWildcards or whatever?

I think it is conceivable but I'm unable to immediately come up with a concrete use case. I can only imagine a few possible predicates in the same vein as `isLiteral` or `hasRecursiveWildcards`, though; I understand your unease but perhaps there are few enough of these predicates that simply adding them as use cases are identified won't lead to a messy API?

**Comment by Deewiant** [comment]
That's quite possible; I can't think of use cases for other predicates either. So for the time being `isLiteral` should be fine to add, and a more general solution can be concocted if things start getting out of hand.

**Comment by sol** [comment]
@Deewiant that sounds great.  `isLiteral` is what I would love to use.

**Comment by hdgarrood** [comment]
I started working on this and I was thinking it might make sense to export this function from `System.FilePath.Glob.Base`, and not to re-export it from `System.FilePath.Glob`. Does that sound reasonable?

**Comment by Deewiant** [comment]
Do you mean `System.FilePath.Glob.Primitive`? The `Base` module is currently not exposed.

Either way, why? I don't see why it couldn't be in `System.FilePath.Glob` directly.

**Comment by hdgarrood** [comment]
Oh yes of course, I forgot that `Base` is not exposed. I was thinking it might make sense to not expose it from there because we aren't yet certain it's the right API and therefore if a better option does turn up, it would be easier to amend the API later if we hadn't already drawn too much attention to it by including it in the most prominent module? But sure, I'll add it to `System.FilePath.Glob` directly.

**Comment by Deewiant** [comment]
@sol Glob-0.9.0 is now on Hackage, with `isLiteral` as well as a bunch of other changes and fixes.

**Comment by hdgarrood** [comment]
:tada: thank you!
